# Generated by Django 5.2.17 on 2026-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
        ('households', '0002_member_member_owed_turns_lte_debt_cap'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('chore_type', 'recurring'), ('frequency', ''), _negated=True), name='chore_recurring_requires_frequency', violation_error_message='A recurring chore must have a frequency (plan.md §3).'),
        ),
    ]
