# Generated by Django 5.2.17 on 2026-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('owed_turns__lte', 7)), name='member_owed_turns_lte_debt_cap', violation_error_message='owed_turns cannot exceed the debt cap of 7 (plan.md §5.2).'),
        ),
    ]
